### PR TITLE
Fix parallel unique boundary ids

### LINKED ISSUE #329: computeUniqueBoundaryIds not called in/after loadBalance
This prevents using `boundarySegmentIndex`.

### PR DESCRIPTION
**Pull request by blattms**
these were not correctly scattered when loadbalancing the grid. Actually we did set them up but in a temporary vector that was eventually thrown away. Now we store it as we are supposed to do. Added a test
for the boundary ids, too.

Closes #329

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Any chance this will effect convergence/performance on MPI runs?

**Comment by bska** [comment]
Having unique boundary IDs is an essential prerequisite to using periodic boundary conditions for relative permeability upscaling in module opm-upscaling.

**Comment by alfbr** [comment]
Ah, right, thanks for the clarification!

**Comment by atgeirr** [comment]
Of course, the upscaling codes do not use a distributed grid... Which is why this was not discovered before. I'll merge!

File: tests/cpgrid/distribution_test.cpp [hunk 1]
```diff
@@ -485,6 +485,9 @@ init_unit_test_func()
 int main(int argc, char** argv)
 {
     Dune::MPIHelper::instance(argc, argv);
+    MPI_Errhandler errhandler;
```
Comment (akva2) [inline tests/cpgrid/distribution_test.cpp]: missing HAVE_MPI protection is seems, see https://ci.opm-project.org/job/opm-grid/103/

**Comment by blattms** [comment]
Thanks a lot for noticing and sorry for carelessness. Posted #337 to fix this.
