### PR TITLE
Fixes bugs in movement of wells when loadbalancing

### LINKED ISSUE #476: Segmentation fault with MPI occuring in opm-grid/opm/grid/common/WellConnections.cpp
Long story short: ```flow``` fails when running in MPI (and typically fails more often with more processes being used).

This bug is a bit tricky to reproduce, and does not always trigger (which is to be expected by what I suspect is a memory access violation). It seems to be easier to trigger with more processes.

# Steps to reproduce
## Overview

- Executable: ```flow``` from ```opm-simulators``` at commit ```c977a28cfa6077722be79ccfba0b03d9387f7c52```
- Build type: Release and RelWithDebInfo
- Input file: ```opm-data/norne/NORNE_ATW2013.DATA``` from github.com/opm/opm-data at ```4acef48e5a76b96886791230b83003259de0691a``` (latest commit)

## Failing command 
Where ```NUMBER_OF_PROCS>= 16```
```bash
mpirun -np ${NUMBER_OF_PROCS} flow NORNE_ATW2013.DATA --threads-per-process=1 
--output-dir=output
```
## Behaviour:
Gives Segmentation fault in setup phase (see end of bug report for a detailed output).

## Expected behaviour:
Simulation should run to the end without segmentation fault. 

# Attempts at debugging
To trace the segmentation fault, I inserted a signal handler to the signal ```SIGSEV``` in ```opm-simulators/flow/flow.cpp```. The segmentation faults consistently appear in ```opm-grid/opm/grid/common/WellConnections.cpp``` in the function ```postProcessPartitioningForWells```. 

Further attempts to discover the exact line number (by simply printing out each line executed), points to the line 172 and 182. The common theme here is the usage of iterators on modified vectors, where the code essentially does:
```cpp
auto middle = someVector.end();
someVector.push_back(something);
someFunction(..., middle, ...);
```
this can [invalidate](https://thispointer.com/stdvector-and-iterator-invalidation/) the iterator (since the vector can change memory location). 

# Suggested solution
Fix the usage of iterators in ```WellConnections.cpp``` such that there is no undefined behaviour present.

# Further details
## Setup
Machine: saga.sigma2.no (Norwegian compute cluster)
Modules loaded (contains versions of relevant compilers etc):

```bash
module list

Currently Loaded Modules:
  1) StdEnv                                               (S)
  2) GCCcore/8.2.0
  3) zlib/1.2.11-GCCcore-8.2.0                            (H)
  4) binutils/2.31.1-GCCcore-8.2.0                        (H)
  5) icc/2019.1.144-GCC-8.2.0-2.31.1
  6) ifort/2019.1.144-GCC-8.2.0-2.31.1
  7) iccifort/2019.1.144-GCC-8.2.0-2.31.1
  8) impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1
  9) iimpi/2019a
 10) imkl/2019.1.144-iimpi-2019a
 11) intel/2019a
 12) METIS/5.1.0-GCCcore-8.2.0
 13) SuiteSparse/5.4.0-intel-2019a-METIS-5.1.0
 14) GCC/8.2.0-2.31.1
 15) OpenBLAS/0.3.5-GCC-8.2.0-2.31.1
 16) bzip2/1.0.6-GCCcore-8.2.0                            (H)
 17) ncurses/6.1-GCCcore-8.2.0                            (H)
 18) libreadline/8.0-GCCcore-8.2.0                        (H)
 19) XZ/5.2.4-GCCcore-8.2.0                               (H)
 20) GMP/6.1.2-GCCcore-8.2.0                              (H)
 21) libffi/3.2.1-GCCcore-8.2.0                           (H)
 22) Python/3.7.2-GCCcore-8.2.0
```

Boost version: 1.73.0
Dune: 2.6
Trilinos: 12.8.1
Compiler: gcc-8.2.0

# Full output
Notice this is with an exception handler that prints the stack trace on ```SIGSEV``` (signal 11)
Signal 15 is from the application timing out when one process dies. 

```bash
Starting job 873290 on c1-[29,31],c2-[33,35,55],c3-8 at Thu Jun 11 19:17:16 CEST 2020

  1) StdEnv

Currently Loaded Modules:
  1) StdEnv                                               (S)
  2) GCCcore/8.2.0
  3) zlib/1.2.11-GCCcore-8.2.0                            (H)
  4) binutils/2.31.1-GCCcore-8.2.0                        (H)
  5) icc/2019.1.144-GCC-8.2.0-2.31.1
  6) ifort/2019.1.144-GCC-8.2.0-2.31.1
  7) iccifort/2019.1.144-GCC-8.2.0-2.31.1
  8) impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1
  9) iimpi/2019a
 10) imkl/2019.1.144-iimpi-2019a
 11) intel/2019a
 12) METIS/5.1.0-GCCcore-8.2.0
 13) SuiteSparse/5.4.0-intel-2019a-METIS-5.1.0
 14) GCC/8.2.0-2.31.1
 15) OpenBLAS/0.3.5-GCC-8.2.0-2.31.1
 16) bzip2/1.0.6-GCCcore-8.2.0                            (H)
 17) ncurses/6.1-GCCcore-8.2.0                            (H)
 18) libreadline/8.0-GCCcore-8.2.0                        (H)
 19) XZ/5.2.4-GCCcore-8.2.0                               (H)
 20) GMP/6.1.2-GCCcore-8.2.0                              (H)
 21) libffi/3.2.1-GCCcore-8.2.0                           (H)
 22) Python/3.7.2-GCCcore-8.2.0

  Where:
   H:  Hidden Module
   S:  Module is Sticky, requires --force to unload or purge

 

**********************************************************************
*                                                                    *
*                      This is flow 2020.10-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see https://opm-project.org         *
*                                                                    *
**********************************************************************

Using 22 MPI processes with 1 OMP threads on each 

Reading deck file 'norne/NORNE_ATW2013.DATA'
    0 Reading RUNSPEC  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 9
    1 Reading DIMENS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 11
    2 Reading GRIDOPTS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 16
    3 Reading OIL      in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 19
    4 Reading WATER    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 21
    5 Reading GAS      in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 23
    6 Reading DISGAS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 25
    7 Reading VAPOIL   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 27
    8 Reading ENDSCALE in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 29
    9 Reading METRIC   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 32
   10 Reading SATOPTS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 34
   11 Reading START    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 37
   12 Reading EQLDIMS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 40
   13 Reading EQLOPTS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 43
   14 Reading REGDIMS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 46
   15 Reading TRACERS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 50
   16 Reading WELLDIMS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 54
   17 Reading TABDIMS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 57
   18 Reading VFPIDIMS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 62
   19 Reading VFPPDIMS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 93
   20 Reading FAULTDIM in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 96
   21 Reading PIMTDIMS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 99
   22 Reading NSTACK   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 102
   23 Reading UNIFIN   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 105
   24 Reading UNIFOUT  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 106
   25 Reading OPTIONS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 111
   26 Reading GRID     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 119
   27 Reading NEWTRAN  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 121
   28 Reading GRIDFILE in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 124
   29 Reading MAPAXES  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 128
   30 Reading GRIDUNIT in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 131
   31 Reading INIT     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 135
   32 Reading MESSAGES in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 137
   33 Reading PINCH    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 140
   34 Reading NOECHO   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 143
   35 Reading SPECGRID in file /cluster/work/jobs/873290/norne/INCLUDE/GRID/IRAP_1005.GRDECL, line 10
   36 Reading COORD    in file /cluster/work/jobs/873290/norne/INCLUDE/GRID/IRAP_1005.GRDECL, line 39
   37 Reading ZCORN    in file /cluster/work/jobs/873290/norne/INCLUDE/GRID/IRAP_1005.GRDECL, line 5379
   38 Reading ACTNUM   in file /cluster/work/jobs/873290/norne/INCLUDE/GRID/ACTNUM_0704.prop, line 8
   39 Reading FAULTS   in file /cluster/work/jobs/873290/norne/INCLUDE/FAULT/FAULT_JUN_05.INC, line 9
   40 Reading MULTFLT  in file /cluster/work/jobs/873290/norne/INCLUDE/FAULT/FAULTMULT_AUG-2006.INC, line 8
   41 Reading PORO     in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/PORO_0704.prop, line 9
   42 Reading NTG      in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/NTG_0704.prop, line 9
   43 Reading PERMX    in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/PERM_0704.prop, line 9
   44 Reading COPY     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 184
   45 Reading MULTIPLY in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 190
   46 Reading MULTZ    in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_HM_1.INC, line 9
   47 Reading EQUALS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 231
   48 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 9
   49 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 15
   50 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 40
   51 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 68
   52 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 76
   53 Reading EQUALS   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTZ_JUN_05_MOD.INC, line 81
   54 Reading FLUXNUM  in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/FLUXNUM_0704.prop, line 9
   55 Reading MULTREGT in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/MULTREGT_D_27.prop, line 45
   56 Reading NOECHO   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 252
   57 Reading MINPV    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 254
   58 Reading EDIT     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 257
   59 Reading PROPS    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 262
   60 Reading NOECHO   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 269
   61 Reading PVTG     in file /cluster/work/jobs/873290/norne/INCLUDE/PVT/PVT-WET-GAS.INC, line 8
   62 Reading PVTO     in file /cluster/work/jobs/873290/norne/INCLUDE/PVT/PVT-WET-GAS.INC, line 220
   63 Reading ROCK     in file /cluster/work/jobs/873290/norne/INCLUDE/PVT/PVT-WET-GAS.INC, line 530
   64 Reading PVTW     in file /cluster/work/jobs/873290/norne/INCLUDE/PVT/PVT-WET-GAS.INC, line 539
   65 Reading DENSITY  in file /cluster/work/jobs/873290/norne/INCLUDE/PVT/PVT-WET-GAS.INC, line 546
   66 Reading TRACER   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 274
   67 Reading BOX      in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/SWINITIAL.INC, line 8
   68 Reading SWATINIT in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/SWINITIAL.INC, line 11
   69 Reading ENDBOX   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/SWINITIAL.INC, line 28349
   70 Reading SWOF     in file /cluster/work/jobs/873290/norne/INCLUDE/RELPERM/SCAL_NORNE.INC, line 8
   71 Reading SGOF     in file /cluster/work/jobs/873290/norne/INCLUDE/RELPERM/SCAL_NORNE.INC, line 59
   72 Reading SCALECRS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 292
   73 Reading EQUALS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 296
   74 Reading COPY     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 308
   75 Reading ADD      in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 314
   76 Reading MULTIPLY in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 319
   77 Reading ADD      in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 323
   78 Reading EQUALS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 327
   79 Reading EHYSTR   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 336
   80 Reading COPY     in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 339
   81 Reading EQUALS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 349
   82 Reading RPTPROPS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 353
   83 Reading REGIONS  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 358
   84 Reading FIPNUM   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/FIPNUM_0704.prop, line 9
   85 Reading EQUALS   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 364
   86 Reading EQLNUM   in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/EQLNUM_0704.prop, line 9
   87 Reading SOLUTION in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 379
   88 Reading RPTRST   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 381
   89 Reading RPTSOL   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 384
   90 Reading EQUIL    in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/E3.prop, line 16
   91 Reading RSVD     in file /cluster/work/jobs/873290/norne/INCLUDE/PETRO/E3.prop, line 24
   92 Reading THPRES   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 394
   93 Reading TVDPFSEA in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 404
   94 Reading TVDPFHTO in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 407
   95 Reading TVDPFS36 in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 410
   96 Reading TVDPF2FB in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 413
   97 Reading TVDPF4FB in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 416
   98 Reading TVDPFDFB in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 419
   99 Reading TVDPFTFB in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 422
  100 Reading SUMMARY  in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 428
  101 Reading NEWTON   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 430
  102 Reading MLINEARS in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 431
  103 Reading DATE     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 9
  104 Reading PERFORMA in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 10
  105 Reading FVPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 14
  106 Reading FWPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 15
  107 Reading FWPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 16
  108 Reading FOPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 17
  109 Reading FOPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 18
  110 Reading FGPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 19
  111 Reading FGPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 20
  112 Reading FLPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 21
  113 Reading FLPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 22
  114 Reading FGSR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 23
  115 Reading FGCR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 24
  116 Reading FVIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 27
  117 Reading FWIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 28
  118 Reading FWIRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 29
  119 Reading FGIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 30
  120 Reading FGIRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 31
  121 Reading FVPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 33
  122 Reading FWPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 34
  123 Reading FOPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 35
  124 Reading FLPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 36
  125 Reading FLPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 37
  126 Reading FGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 38
  127 Reading FOPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 39
  128 Reading FGPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 40
  129 Reading FWPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 41
  130 Reading FGST     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 42
  131 Reading FGCT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 43
  132 Reading FVIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 45
  133 Reading FWIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 46
  134 Reading FWITH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 47
  135 Reading FGIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 48
  136 Reading FGITH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 49
  137 Reading FWIP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 51
  138 Reading FOIP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 52
  139 Reading FGIP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 53
  140 Reading FWCT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 55
  141 Reading FWCTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 56
  142 Reading FGOR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 57
  143 Reading FGORH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 58
  144 Reading FPR      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 60
  145 Reading RPR      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 66
  146 Reading ROPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 68
  147 Reading RGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 70
  148 Reading RWPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 72
  149 Reading RGFT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 74
  150 Reading RWFT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 76
  151 Reading ROIP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 78
  152 Reading ROP      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 80
  153 Reading GPR      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 83
  154 Reading GOPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 85
  155 Reading GGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 87
  156 Reading GWPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 89
  157 Reading GOPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 91
  158 Reading GLPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 93
  159 Reading GGPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 95
  160 Reading GWPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 97
  161 Reading GGIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 99
  162 Reading GGIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 101
  163 Reading GWCT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 103
  164 Reading GGOR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 105
  165 Reading GWIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 107
  166 Reading WWPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 111
  167 Reading WWPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 113
  168 Reading WOPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 115
  169 Reading WOPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 117
  170 Reading WGPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 119
  171 Reading WGPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 121
  172 Reading WLPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 123
  173 Reading WLPRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 125
  174 Reading WLPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 128
  175 Reading WLPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 131
  176 Reading WWIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 135
  177 Reading WWIRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 138
  178 Reading WGIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 141
  179 Reading WGIRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 145
  180 Reading WGIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 149
  181 Reading WGIRH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 153
  182 Reading WWPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 157
  183 Reading WWPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 159
  184 Reading WOPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 161
  185 Reading WOPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 163
  186 Reading WGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 165
  187 Reading WGPTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 167
  188 Reading WWIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 175
  189 Reading WWCT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 179
  190 Reading WWCTH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 181
  191 Reading WGOR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 183
  192 Reading WGORH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 185
  193 Reading WGORH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 187
  194 Reading WBHP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 190
  195 Reading WBHPH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 192
  196 Reading WTHP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 194
  197 Reading WTHPH    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 196
  198 Reading WPI      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 198
  199 Reading WBP      in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 200
  200 Reading WBP4     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 202
  201 Reading CWIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 205
  202 Reading CWIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 215
  203 Reading CGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 226
  204 Reading CGFR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 229
  205 Reading CWFR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 232
  206 Reading FTPRSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 12
  207 Reading FTPRHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 13
  208 Reading FTPRS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 14
  209 Reading FTPR2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 15
  210 Reading FTPR4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 16
  211 Reading FTPRDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 17
  212 Reading FTPRTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 18
  213 Reading FTPCSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 20
  214 Reading FTPCHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 21
  215 Reading FTPCS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 22
  216 Reading FTPC2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 23
  217 Reading FTPC4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 24
  218 Reading FTPCDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 25
  219 Reading FTPCTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 26
  220 Reading FTIRSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 28
  221 Reading FTIRHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 29
  222 Reading FTIRS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 30
  223 Reading FTIR2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 31
  224 Reading FTIR4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 32
  225 Reading FTIRDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 33
  226 Reading FTIRTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 34
  227 Reading FTPTSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 36
  228 Reading FTPTHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 37
  229 Reading FTPTS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 38
  230 Reading FTPT2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 39
  231 Reading FTPT4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 40
  232 Reading FTPTDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 41
  233 Reading FTPTTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 42
  234 Reading FTITSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 44
  235 Reading FTITHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 45
  236 Reading FTITS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 46
  237 Reading FTIT2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 47
  238 Reading FTIT4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 48
  239 Reading FTITDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 49
  240 Reading FTITTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 50
  241 Reading WTPRSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 53
  242 Reading WTPRHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 55
  243 Reading WTPRS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 57
  244 Reading WTPR2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 59
  245 Reading WTPR4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 61
  246 Reading WTPRDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 63
  247 Reading WTPRTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 65
  248 Reading WTPCSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 68
  249 Reading WTPCHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 70
  250 Reading WTPCS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 72
  251 Reading WTPC2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 74
  252 Reading WTPC4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 76
  253 Reading WTPCDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 78
  254 Reading WTPCTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 80
  255 Reading WTIRSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 84
  256 Reading WTIRHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 87
  257 Reading WTIRS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 90
  258 Reading WTIR2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 93
  259 Reading WTIR4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 96
  260 Reading WTIRDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 99
  261 Reading WTIRTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 102
  262 Reading WTPTSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 106
  263 Reading WTPTHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 108
  264 Reading WTPTS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 110
  265 Reading WTPT2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 112
  266 Reading WTPT4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 114
  267 Reading WTPTDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 116
  268 Reading WTPTTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 118
  269 Reading WTITSEA  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 121
  270 Reading WTITHTO  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 124
  271 Reading WTITS36  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 127
  272 Reading WTIT2FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 130
  273 Reading WTIT4FB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 133
  274 Reading WTITDFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 136
  275 Reading WTITTFB  in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/tracer.data, line 139
  276 Reading RGIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 8
  277 Reading RGPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 10
  278 Reading RGIPG    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 12
  279 Reading RGIPL    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 14
  280 Reading RGIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 17
  281 Reading RGPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 19
  282 Reading RWIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 21
  283 Reading RWPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 23
  284 Reading RWPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 25
  285 Reading RWIP     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 27
  286 Reading ROPR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 29
  287 Reading ROIR     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 31
  288 Reading ROIT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 33
  289 Reading ROIPG    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 35
  290 Reading ROIPL    in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 37
  291 Reading ROPT     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/gas.inc, line 40
  292 Reading WBP5     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/wpave.inc, line 9
  293 Reading WBP9     in file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/wpave.inc, line 12
  294 Reading SCHEDULE in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 455
  295 Reading DRSDT    in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 458
  296 Reading NOECHO   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 461
  297 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/DevNew.VFP, line 9
  298 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/E1h.VFP, line 56
  299 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/NEW_D2_GAS_0.00003.VFP, line 62
  300 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/GAS_PD2.VFP, line 62
  301 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/AlmostVertNew.VFP, line 9
  302 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/GasProd.VFP, line 12
  303 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B1BH.Ecl, line 68
  304 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B2H.Ecl, line 68
  305 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B3H.Ecl, line 68
  306 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B4DH.Ecl, line 68
  307 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D1CH.Ecl, line 68
  308 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D2H.Ecl, line 68
  309 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D3BH.Ecl, line 68
  310 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/E1H.Ecl, line 68
  311 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/E3CH.Ecl, line 68
  312 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/K3H.Ecl, line 68
  313 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/pd2.VFP, line 53
  314 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/pe2.VFP, line 53
  315 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PB1.PIPE.Ecl, line 68
  316 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PB2.PIPE.Ecl, line 68
  317 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PD1.PIPE.Ecl, line 68
  318 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PD2.PIPE.Ecl, line 68
  319 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PE1.PIPE.Ecl, line 68
  320 Reading VFPPROD  in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PE2.PIPE.Ecl, line 68
  321 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/WIC.PIPE.Ecl, line 66
  322 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/WIF.PIPE.Ecl, line 66
  323 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/C1H.Ecl, line 62
  324 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/C2H.Ecl, line 62
  325 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/C3H.Ecl, line 62
  326 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/C4H.Ecl, line 62
  327 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/C4AH.Ecl, line 62
  328 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/F1H.Ecl, line 66
  329 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/F2H.Ecl, line 62
  330 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/F3H.Ecl, line 62
  331 Reading VFPINJ   in file /cluster/work/jobs/873290/norne/INCLUDE/VFP/F4H.Ecl, line 62
  332 Reading TUNING   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 628
  333 Reading ZIPPY2   in file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 635
  334 Reading PIMULTAB in file /cluster/work/jobs/873290/norne/INCLUDE/PI/pimultab_low-high_aug-2006.inc, line 8
  335 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 124
  336 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 130
  337 Reading GRUPTREE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 152
  338 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 170
  339 Reading WPAVE    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 176
  340 Reading GRUPNET  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 180
  341 Reading VAPPARS  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 195
  342 Reading NETBALAN in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 199
  343 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 204
  344 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 208
  345 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 212
  346 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 216
  347 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 221
  348 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 225
  349 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 230
  350 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 235
  351 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 269
  352 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 273
  353 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 286
  354 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 292
  355 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 297
  356 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 301
  357 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 307
  358 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 311
  359 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 316
  360 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 320
  361 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 326
  362 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 330
  363 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 337
  364 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 341
  365 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 347
  366 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 352
  367 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 384
  368 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 388
  369 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 412
  370 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 419
  371 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 423
  372 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 427
  373 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 432
  374 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 440
  375 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 444
  376 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 450
  377 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 455
  378 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 459
  379 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 465
  380 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 469
  381 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 474
  382 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 486
  383 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 493
  384 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 500
  385 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 504
  386 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 511
  387 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 515
  388 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 522
  389 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 527
  390 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 565
  391 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 569
  392 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 599
  393 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 607
  394 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 611
  395 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 615
  396 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 620
  397 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 628
  398 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 632
  399 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 639
  400 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 644
  401 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 648
  402 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 655
  403 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 660
  404 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 685
  405 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 696
  406 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 704
  407 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 709
  408 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 743
  409 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 747
  410 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 772
  411 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 781
  412 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 786
  413 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 791
  414 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 800
  415 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 804
  416 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 812
  417 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 817
  418 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 821
  419 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 829
  420 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 833
  421 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 838
  422 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 862
  423 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 870
  424 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 878
  425 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 883
  426 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 887
  427 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 894
  428 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 898
  429 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 906
  430 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 912
  431 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 946
  432 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 950
  433 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 974
  434 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 983
  435 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 987
  436 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 992
  437 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 997
  438 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1005
  439 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1009
  440 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1017
  441 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1023
  442 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1027
  443 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1035
  444 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1041
  445 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1074
  446 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1085
  447 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1094
  448 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1100
  449 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1104
  450 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1113
  451 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1118
  452 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1123
  453 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1127
  454 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1136
  455 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1141
  456 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1146
  457 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1153
  458 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1157
  459 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1166
  460 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1171
  461 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1178
  462 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1189
  463 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1195
  464 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1204
  465 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1210
  466 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1214
  467 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1223
  468 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1229
  469 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1233
  470 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1242
  471 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1248
  472 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1278
  473 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1282
  474 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1291
  475 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1300
  476 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1306
  477 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1310
  478 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1319
  479 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1324
  480 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1329
  481 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1333
  482 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1342
  483 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1347
  484 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1353
  485 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1358
  486 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1362
  487 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1371
  488 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1376
  489 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1381
  490 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1393
  491 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1397
  492 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1404
  493 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1413
  494 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1419
  495 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1424
  496 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1428
  497 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1437
  498 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1444
  499 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1448
  500 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1457
  501 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1463
  502 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1467
  503 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1472
  504 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1476
  505 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1485
  506 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1492
  507 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1496
  508 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1505
  509 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1511
  510 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1516
  511 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1520
  512 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1529
  513 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1535
  514 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1540
  515 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1559
  516 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1563
  517 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1575
  518 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1585
  519 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1592
  520 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1623
  521 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1627
  522 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1645
  523 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1654
  524 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1661
  525 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1665
  526 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1674
  527 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1680
  528 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1685
  529 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1689
  530 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1699
  531 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1705
  532 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1712
  533 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1746
  534 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1750
  535 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1775
  536 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1786
  537 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1793
  538 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1798
  539 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1807
  540 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1811
  541 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1821
  542 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1828
  543 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1858
  544 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1868
  545 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1879
  546 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1886
  547 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1916
  548 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1920
  549 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1941
  550 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1951
  551 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1959
  552 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1963
  553 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1967
  554 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1972
  555 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1980
  556 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1984
  557 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1994
  558 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2002
  559 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2006
  560 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2016
  561 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2024
  562 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2060
  563 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2064
  564 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2080
  565 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2091
  566 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2099
  567 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2103
  568 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2113
  569 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2120
  570 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2125
  571 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2153
  572 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2157
  573 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2169
  574 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2179
  575 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2186
  576 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2193
  577 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2197
  578 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2207
  579 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2215
  580 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2226
  581 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2230
  582 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2239
  583 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2249
  584 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2257
  585 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2292
  586 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2305
  587 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2316
  588 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2324
  589 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2328
  590 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2338
  591 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2346
  592 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2351
  593 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2380
  594 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2384
  595 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2398
  596 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2409
  597 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2418
  598 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2422
  599 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2433
  600 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2440
  601 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2447
  602 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2451
  603 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2461
  604 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2469
  605 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2476
  606 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2480
  607 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2490
  608 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2498
  609 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2503
  610 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2533
  611 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2537
  612 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2560
  613 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2571
  614 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2580
  615 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2584
  616 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2591
  617 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2598
  618 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2602
  619 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2613
  620 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2622
  621 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2654
  622 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2667
  623 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2678
  624 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2687
  625 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2692
  626 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2696
  627 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2706
  628 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2715
  629 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2720
  630 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2724
  631 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2734
  632 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2744
  633 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2748
  634 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2757
  635 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2765
  636 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2770
  637 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2774
  638 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2785
  639 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2794
  640 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2799
  641 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2827
  642 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2831
  643 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2844
  644 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2856
  645 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2866
  646 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2870
  647 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2883
  648 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2893
  649 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2897
  650 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2910
  651 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2919
  652 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2924
  653 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2928
  654 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2941
  655 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2950
  656 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2957
  657 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2961
  658 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2974
  659 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2984
  660 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3006
  661 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3010
  662 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3024
  663 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3036
  664 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3040
  665 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3046
  666 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3051
  667 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3059
  668 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3063
  669 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3075
  670 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3085
  671 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3089
  672 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3101
  673 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3110
  674 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3115
  675 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3119
  676 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3131
  677 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3140
  678 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3147
  679 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3182
  680 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3186
  681 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3202
  682 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3213
  683 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3223
  684 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3227
  685 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3238
  686 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3248
  687 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3252
  688 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3256
  689 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3268
  690 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3278
  691 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3288
  692 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3292
  693 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3297
  694 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3309
  695 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3319
  696 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3323
  697 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3335
  698 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3344
  699 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3349
  700 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3353
  701 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3365
  702 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3374
  703 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3381
  704 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3417
  705 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3421
  706 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3449
  707 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3461
  708 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3465
  709 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3474
  710 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3479
  711 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3487
  712 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3491
  713 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3502
  714 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3512
  715 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3532
  716 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3536
  717 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3552
  718 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3564
  719 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3574
  720 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3578
  721 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3589
  722 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3598
  723 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3605
  724 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3609
  725 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3621
  726 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3630
  727 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3637
  728 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3641
  729 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3653
  730 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3663
  731 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3698
  732 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3702
  733 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3729
  734 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3741
  735 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3751
  736 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3756
  737 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3764
  738 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3768
  739 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3779
  740 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3789
  741 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3802
  742 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3807
  743 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3819
  744 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3829
  745 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3845
  746 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3849
  747 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3858
  748 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3869
  749 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3879
  750 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3884
  751 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3888
  752 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3899
  753 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3909
  754 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3914
  755 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3918
  756 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3929
  757 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3939
  758 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3946
  759 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3969
  760 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3973
  761 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3984
  762 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3996
  763 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4007
  764 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4011
  765 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4025
  766 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4035
  767 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4040
  768 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4044
  769 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4058
  770 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4068
  771 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4075
  772 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4079
  773 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4092
  774 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4103
  775 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4107
  776 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4120
  777 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4130
  778 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4135
  779 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4139
  780 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4151
  781 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4161
  782 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4168
  783 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4172
  784 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4176
  785 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4187
  786 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4198
  787 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4202
  788 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4213
  789 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4224
  790 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4265
  791 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4269
  792 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4302
  793 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4314
  794 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4318
  795 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4328
  796 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4333
  797 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4341
  798 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4345
  799 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4356
  800 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4367
  801 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4371
  802 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4382
  803 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4392
  804 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4397
  805 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4401
  806 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4413
  807 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4423
  808 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4428
  809 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4432
  810 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4444
  811 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4454
  812 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4459
  813 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4488
  814 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4492
  815 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4514
  816 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4526
  817 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4537
  818 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4541
  819 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4548
  820 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4556
  821 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4560
  822 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4571
  823 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4582
  824 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4586
  825 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4597
  826 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4607
  827 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4612
  828 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4616
  829 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4628
  830 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4638
  831 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4643
  832 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4665
  833 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4669
  834 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4683
  835 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4696
  836 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4707
  837 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4711
  838 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4724
  839 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4735
  840 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4752
  841 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4759
  842 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4773
  843 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4784
  844 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4788
  845 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4800
  846 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4810
  847 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4815
  848 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4819
  849 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4830
  850 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4841
  851 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4845
  852 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4856
  853 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4867
  854 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4871
  855 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4876
  856 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4880
  857 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4891
  858 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4902
  859 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4907
  860 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4911
  861 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4922
  862 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4933
  863 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4940
  864 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4944
  865 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4955
  866 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4967
  867 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4971
  868 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4981
  869 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4992
  870 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4997
  871 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5001
  872 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5015
  873 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5026
  874 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5031
  875 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5035
  876 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5049
  877 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5060
  878 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5067
  879 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5071
  880 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5083
  881 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5094
  882 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5099
  883 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5103
  884 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5116
  885 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5127
  886 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5132
  887 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5136
  888 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5149
  889 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5161
  890 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5165
  891 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5178
  892 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5189
  893 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5194
  894 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5198
  895 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5202
  896 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5215
  897 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5226
  898 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5233
  899 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5237
  900 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5250
  901 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5262
  902 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5266
  903 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5278
  904 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5289
  905 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5294
  906 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5318
  907 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5322
  908 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5336
  909 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5347
  910 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5358
  911 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5364
  912 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5369
  913 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5373
  914 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5384
  915 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5395
  916 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5400
  917 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5404
  918 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5416
  919 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5427
  920 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5432
  921 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5436
  922 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5449
  923 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5461
  924 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5465
  925 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5479
  926 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5490
  927 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5495
  928 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5499
  929 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5512
  930 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5524
  931 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5528
  932 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5541
  933 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5552
  934 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5557
  935 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5569
  936 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5573
  937 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5578
  938 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5591
  939 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5603
  940 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5607
  941 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5619
  942 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5630
  943 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5635
  944 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5639
  945 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5653
  946 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5663
  947 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5669
  948 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5674
  949 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5678
  950 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5691
  951 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5702
  952 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5707
  953 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5711
  954 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5724
  955 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5736
  956 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5740
  957 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5744
  958 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5755
  959 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5767
  960 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5771
  961 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5783
  962 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5794
  963 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5798
  964 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5810
  965 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5820
  966 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5825
  967 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5829
  968 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5840
  969 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5850
  970 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5855
  971 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5859
  972 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5870
  973 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5880
  974 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5886
  975 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5891
  976 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5895
  977 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5906
  978 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5916
  979 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5921
  980 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5925
  981 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5937
  982 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5947
  983 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5952
  984 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5956
  985 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5968
  986 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5979
  987 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5983
  988 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5995
  989 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6005
  990 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6010
  991 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6014
  992 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6026
  993 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6037
  994 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6043
  995 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6047
  996 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6056
  997 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6067
  998 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6080
  999 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6086
 1000 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6098
 1001 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6109
 1002 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6113
 1003 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6126
 1004 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6136
 1005 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6141
 1006 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6145
 1007 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6158
 1008 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6169
 1009 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6176
 1010 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6180
 1011 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6193
 1012 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6205
 1013 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6224
 1014 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6228
 1015 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6238
 1016 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6250
 1017 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6261
 1018 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6265
 1019 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6277
 1020 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6287
 1021 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6292
 1022 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6296
 1023 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6309
 1024 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6319
 1025 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6325
 1026 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6330
 1027 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6334
 1028 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6347
 1029 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6358
 1030 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6362
 1031 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6374
 1032 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6384
 1033 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6389
 1034 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6393
 1035 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6405
 1036 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6415
 1037 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6419
 1038 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6424
 1039 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6428
 1040 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6432
 1041 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6444
 1042 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6455
 1043 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6459
 1044 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6471
 1045 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6481
 1046 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6486
 1047 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6494
 1048 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6498
 1049 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6510
 1050 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6521
 1051 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6530
 1052 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6535
 1053 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6547
 1054 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6558
 1055 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6569
 1056 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6573
 1057 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6579
 1058 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6591
 1059 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6602
 1060 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6613
 1061 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6617
 1062 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6623
 1063 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6636
 1064 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6648
 1065 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6652
 1066 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6665
 1067 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6676
 1068 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6680
 1069 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6685
 1070 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6722
 1071 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6726
 1072 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6745
 1073 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6759
 1074 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6769
 1075 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6776
 1076 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6780
 1077 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6794
 1078 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6805
 1079 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6809
 1080 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6813
 1081 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6827
 1082 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6838
 1083 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6842
 1084 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6856
 1085 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6867
 1086 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6892
 1087 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6896
 1088 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6915
 1089 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6930
 1090 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6940
 1091 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6945
 1092 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6953
 1093 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6957
 1094 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6971
 1095 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6982
 1096 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6986
 1097 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7000
 1098 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7010
 1099 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7015
 1100 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7019
 1101 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7033
 1102 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7043
 1103 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7048
 1104 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7052
 1105 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7066
 1106 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7076
 1107 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7082
 1108 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7087
 1109 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7109
 1110 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7119
 1111 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7132
 1112 Reading WTRACER  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7143
 1113 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7147
 1114 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7152
 1115 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7156
 1116 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7169
 1117 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7181
 1118 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7185
 1119 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7199
 1120 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7211
 1121 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7215
 1122 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7228
 1123 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7239
 1124 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7244
 1125 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7248
 1126 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7261
 1127 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7272
 1128 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7279
 1129 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7283
 1130 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7296
 1131 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7308
 1132 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7312
 1133 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7325
 1134 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7336
 1135 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7341
 1136 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7370
 1137 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7374
 1138 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7389
 1139 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7404
 1140 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7415
 1141 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7422
 1142 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7426
 1143 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7441
 1144 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7452
 1145 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7457
 1146 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7461
 1147 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7476
 1148 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7488
 1149 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7492
 1150 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7507
 1151 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7518
 1152 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7523
 1153 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7527
 1154 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7540
 1155 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7551
 1156 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7556
 1157 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7560
 1158 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7575
 1159 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7587
 1160 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7591
 1161 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7606
 1162 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7617
 1163 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7622
 1164 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7626
 1165 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7641
 1166 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7652
 1167 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7657
 1168 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7661
 1169 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7676
 1170 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7687
 1171 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7694
 1172 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7698
 1173 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7713
 1174 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7725
 1175 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7729
 1176 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7744
 1177 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7755
 1178 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7760
 1179 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7768
 1180 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7772
 1181 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7787
 1182 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7798
 1183 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7805
 1184 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7809
 1185 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7823
 1186 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7834
 1187 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7839
 1188 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7843
 1189 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7856
 1190 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7868
 1191 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7872
 1192 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7886
 1193 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7898
 1194 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7932
 1195 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7936
 1196 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7966
 1197 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7981
 1198 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7985
 1199 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7996
 1200 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8001
 1201 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8008
 1202 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8012
 1203 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8026
 1204 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8038
 1205 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8042
 1206 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8056
 1207 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8067
 1208 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8072
 1209 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8093
 1210 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8097
 1211 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8109
 1212 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8124
 1213 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8135
 1214 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8142
 1215 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8146
 1216 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8161
 1217 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8173
 1218 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8177
 1219 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8192
 1220 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8204
 1221 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8208
 1222 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8212
 1223 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8225
 1224 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8237
 1225 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8241
 1226 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8253
 1227 Reading GECON    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8264
 1228 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8269
 1229 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8273
 1230 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8286
 1231 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8297
 1232 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8302
 1233 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8307
 1234 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8311
 1235 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8324
 1236 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8335
 1237 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8342
 1238 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8348
 1239 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8352
 1240 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8357
 1241 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8369
 1242 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8381
 1243 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8385
 1244 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8389
 1245 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8401
 1246 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8413
 1247 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8417
 1248 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8428
 1249 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8440
 1250 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8453
 1251 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8457
 1252 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8468
 1253 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8480
 1254 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8492
 1255 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8513
 1256 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8517
 1257 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8534
 1258 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8548
 1259 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8560
 1260 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8564
 1261 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8577
 1262 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8589
 1263 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8593
 1264 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8597
 1265 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8610
 1266 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8622
 1267 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8626
 1268 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8630
 1269 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8643
 1270 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8653
 1271 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8658
 1272 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8662
 1273 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8675
 1274 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8685
 1275 Reading GCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8691
 1276 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8696
 1277 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8708
 1278 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8712
 1279 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8721
 1280 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8734
 1281 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8738
 1282 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8748
 1283 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8753
 1284 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8759
 1285 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8763
 1286 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8774
 1287 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8785
 1288 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8807
 1289 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8811
 1290 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8821
 1291 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8833
 1292 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8844
 1293 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8848
 1294 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8859
 1295 Reading WTEST    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8869
 1296 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8873
 1297 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8878
 1298 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8882
 1299 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8886
 1300 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8898
 1301 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8908
 1302 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8915
 1303 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8919
 1304 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8931
 1305 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8942
 1306 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8946
 1307 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8950
 1308 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8962
 1309 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8973
 1310 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8977
 1311 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8989
 1312 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9000
 1313 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9004
 1314 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9016
 1315 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9027
 1316 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9032
 1317 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9036
 1318 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9043
 1319 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9055
 1320 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9066
 1321 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9073
 1322 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9077
 1323 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9090
 1324 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9102
 1325 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9106
 1326 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9120
 1327 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9132
 1328 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9136
 1329 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9150
 1330 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9157
 1331 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9162
 1332 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9166
 1333 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9178
 1334 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9185
 1335 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9192
 1336 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9196
 1337 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9207
 1338 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9214
 1339 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9219
 1340 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9223
 1341 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9234
 1342 Reading RPTRST   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9244
 1343 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9249
 1344 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9253
 1345 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9264
 1346 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9275
 1347 Reading WELSPECS in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9294
 1348 Reading COMPDAT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9298
 1349 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9313
 1350 Reading WCONPROD in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9326
 1351 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9330
 1352 Reading WRFTPLT  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9340
 1353 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9345
 1354 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9349
 1355 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9361
 1356 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9371
 1357 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9376
 1358 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9380
 1359 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9384
 1360 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9395
 1361 Reading RPTSCHED in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9405
 1362 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9412
 1363 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9416
 1364 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9429
 1365 Reading WTEST    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9438
 1366 Reading WPITAB   in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9442
 1367 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9447
 1368 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9451
 1369 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9464
 1370 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9474
 1371 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9478
 1372 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9482
 1373 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9495
 1374 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9505
 1375 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9510
 1376 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9522
 1377 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9532
 1378 Reading WELOPEN  in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9536
 1379 Reading WCONHIST in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9540
 1380 Reading WCONINJE in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9554
 1381 Reading DATES    in file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9563
[34;1m
Warning: For keyword 'ENDSCALE' only value REVER in item IRREVERS is supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 29
[0m
[34;1m
Warning: Keyword 'TRACERS' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 50
[0m
[34;1m
Warning: Keyword 'NSTACK' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 102
[0m
[34;1m
Warning: Keyword 'OPTIONS' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 111
[0m
[34;1m
Warning: Keyword 'GRIDUNIT' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 131
[0m
[34;1m
Warning: Keyword 'NOECHO' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 143
[0m
[34;1m
Warning: Keyword 'NOECHO' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 252
[0m
[34;1m
Warning: Keyword 'NOECHO' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 269
[0m
[34;1m
Warning: Keyword 'TRACER' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 274
[0m
[34;1m
Warning: Keyword 'RPTPROPS' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 353
[0m
[34;1m
Warning: Keyword 'RPTSOL' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 384
[0m
[34;1m
Warning: Keyword 'WBP' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 200
[0m
[34;1m
Warning: Keyword 'WBP4' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 202
[0m
[34;1m
Warning: Keyword 'WBP5' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/wpave.inc, line 9
[0m
[34;1m
Warning: Keyword 'WBP9' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/wpave.inc, line 12
[0m
[34;1m
Warning: Keyword 'NOECHO' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 461
[0m
[34;1m
Warning: Keyword 'ZIPPY2' is not supported by flow.
In file /cluster/work/jobs/873290/norne/NORNE_ATW2013.DATA, line 635
[0m
[34;1m
Warning: Keyword 'PIMULTAB' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/PI/pimultab_low-high_aug-2006.inc, line 8
[0m
[34;1m
Warning: Keyword 'WPAVE' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 176
[0m
[34;1m
Warning: Keyword 'GRUPNET' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 180
[0m
[34;1m
Warning: Keyword 'NETBALAN' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 199
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 216
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1118
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1353
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1376
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1467
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1511
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1535
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 1967
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2715
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2765
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 2794
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4392
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4423
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4810
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4871
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 4992
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5364
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5395
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5427
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5490
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5552
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5669
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5702
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5820
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5886
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5916
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 5947
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6005
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6325
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6419
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6481
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 6680
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7010
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7082
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7147
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7452
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7617
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 7834
[0m
[34;1m
Warning: Keyword 'GECON' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 8264
[0m
[34;1m
Warning: Keyword 'WPITAB' is not supported by flow.
In file /cluster/work/jobs/873290/norne/INCLUDE/BC0407_HIST01122006.SCH, line 9442
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 5, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/NEW_D2_GAS_0.00003.VFP, line 62
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 6, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/GAS_PD2.VFP, line 62
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 3, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/AlmostVertNew.VFP, line 9
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 38, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B2H.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 39, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B3H.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 40, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/B4DH.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 41, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D1CH.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 42, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D2H.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 43, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/D3BH.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 47, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/E3CH.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 9, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/pe2.VFP, line 53
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 31, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PB1.PIPE.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 32, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PB2.PIPE.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 33, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PD1.PIPE.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 34, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PD2.PIPE.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 35, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PE1.PIPE.Ecl, line 68
[0m
[34;1m
Warning: VFP table for production wells has BHP versus THP not monotonically increasing.
This may cause convergence issues due to switching between BHP and THP control mode.
In keyword VFPPROD table number 36, file /cluster/work/jobs/873290/norne/INCLUDE/VFP/PE2.PIPE.Ecl, line 68
[0m
SHUT well: B-4H at report step: 8
SHUT well: D-4H at report step: 13
SHUT well: C-1H at report step: 17
SHUT well: E-3H at report step: 22
SHUT well: C-4H at report step: 27
SHUT well: C-4H at report step: 31
SHUT well: B-1H at report step: 42
SHUT well: C-3H at report step: 46
SHUT well: F-1H at report step: 49
SHUT well: C-2H at report step: 53
SHUT well: E-3H at report step: 55
SHUT well: F-2H at report step: 63
SHUT well: E-4H at report step: 75
SHUT well: E-3H at report step: 80
SHUT well: B-4H at report step: 81
SHUT well: D-3H at report step: 85
SHUT well: F-3H at report step: 91
SHUT well: F-3H at report step: 93
SHUT well: B-4H at report step: 102
SHUT well: B-4AH at report step: 105
SHUT well: F-4H at report step: 110
SHUT well: D-1H at report step: 129
SHUT well: B-3H at report step: 132
SHUT well: F-3H at report step: 139
SHUT well: D-4H at report step: 144
SHUT well: B-3H at report step: 154
SHUT well: B-4BH at report step: 165
SHUT well: B-1H at report step: 167
SHUT well: B-1H at report step: 169
SHUT well: B-1H at report step: 170
SHUT well: C-4H at report step: 174
SHUT well: C-4AH at report step: 177
SHUT well: E-3AH at report step: 199
SHUT well: E-3BH at report step: 204
SHUT well: D-3AH at report step: 209
SHUT well: E-2H at report step: 212
SHUT well: E-4AH at report step: 213
STOP well: E-4AH at report step: 214
SHUT well: E-2AH at report step: 219
SHUT well: B-1H at report step: 220
SHUT well: B-1AH at report step: 223
STOP well: D-4AH at report step: 226
OPEN well: D-3BH at report step: 228
STOP well: C-1H at report step: 231
STOP well: C-2H at report step: 231
STOP well: C-3H at report step: 231
STOP well: C-4AH at report step: 231
STOP well: F-4H at report step: 241
STOP well: E-3CH at report step: 244
OPEN well: E-3CH at report step: 246
[34;1m
Warning: Region to region summary keyword: RGFT at /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 74 is ignored[0m
[34;1m
Warning: Region to region summary keyword: RWFT at /cluster/work/jobs/873290/norne/INCLUDE/SUMMARY/summary.data, line 76 is ignored[0m
Manually moving well B-4H to partition 0
Manually moving well D-4H to partition 1
Error: signal 11:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f050a8aa280]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x9948)[0x1743b78]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE8execute_EiPPcbbMS4_FibEb+0xd0)[0xd99060]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm20flowEbosBlackoilMainEiPPcbb+0x129)[0xc10399]
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
Error: signal 15:
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f2f18a29280]
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7fbee9d11280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7f2f223e4a68]
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7ff457f04280]
/lib64/libc.so.6(+0x36280)[0x7fc895234280]
Error: signal 15:
/lib64/libc.so.6(+0x36280)[0x7f804b97e280]
/lib64/libc.so.6(+0x36280)[0x7f6143c16280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f2f22561bd0]
Error: signal 15:
/lib64/libc.so.6(+0x36280)[0x7f088f1a1280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7f614d510c9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a4e)[0x7fc89ebefa4e]
Error: signal 15:
/lib64/libc.so.6(+0x36280)[0x7fad3ef3d280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7fbef360bc9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f2f22325bc8]
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7ff461800bc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7fc89ed6cbd0]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7fad488f8a68]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f614d8c104f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f2f226d404f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f4e03e6d280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7220)[0x7f8055339220]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fbef39bc04f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7fc89eb30bc8]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f5813d05280]
/lib64/libc.so.6(+0x36280)[0x7f3f3b311280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7ff461baf04f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fc89eedf04f]
/lib64/libc.so.6(+0x36280)[0x7f9b5aa9d280]
/lib64/libc.so.6(__sched_yield+0x7)[0x7f088f24dd47]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x230e)[0x7f0898a9dece]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f3482251280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7fad48a75bd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7fad48839bc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fad48be804f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/lib64/libc.so.6(+0x36280)[0x7f28bb71c280]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7fc646870280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f80554b6bd0]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7f28c50d7a68]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f2b83e03280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7246)[0x7f3f44ccc246]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f3f44e49bd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f28c5254bd0]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7fdbcddb0280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2409)[0x7fdbd76acfc9]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f0898e4c04f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f28c5018bc8]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f161b452280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a5f)[0x7f1624e0da5f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f805527abc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f28c53c704f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7fbf8b7ed280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7fbf950e7c9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f3f44c0dbc8]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7f581d5ffc9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f581d9b004f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f805562904f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7f9b64458a68]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f9b645d5bd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f9b64399bc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f3f44fbc04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f72a3)[0x7f348bc0c2a3]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f348bd89bd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f348bb4dbc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f348befc04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7fc65016ac9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fc65051b04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7f2b8d6fdc9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f2b8daae04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fdbd7a5b04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f1624f8abd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f1624d4ebc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f16250fd04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fbf9549804f]
/lib64/libc.so.6(+0x36280)[0x7fa7a45a4280]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xe5)[0x7f4e0d767ca5]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f4e0db1804f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7fa7adf5fa68]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f441102b280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0xde)[0x7f441a925c9e]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f441acd604f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7fa7ae0dcbd0]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7f9b6474804f]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7fa7adea0bc8]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPI_Waitall+0x59f)[0x7fa7ae24f04f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid31postProcessPartitioningForWellsERSt6vectorIiSaIiEERKS3_RKS1_IN3Opm4WellESaIS8_EERKNS0_15WellConnectionsERS1_ISt5tupleIJiicEESaISH_EERS1_ISG_IJiiciEESaISL_EERKNS_23CollectiveCommunicationIiEE+0x33a2)[0x173d5d2]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6cpgrid30zoltanGraphPartitionGridOnRootB5cxx11ERKNS_6CpGridEPKSt6vectorIN3Opm4WellESaIS6_EEPKdRKNS_23CollectiveCommunicationIiEENS_16EdgeWeightMethodEi+0x8df)[0x1746d6f]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm12FlowMainEbosINS_10Properties4TTag14EclFlowProblemEE18setupEbosSimulatorEv+0x28)[0xd98798]
slurmstepd: error: *** JOB 873290 ON c1-29 CANCELLED AT 2020-06-11T20:17:20 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 873290.0 ON c1-29 CANCELLED AT 2020-06-11T20:17:20 DUE TO TIME LIMIT ***
Error: signal 15:
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_Z7handleri+0x25)[0xbeebc5]
/lib64/libc.so.6(+0x36280)[0x7f050a8aa280]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1f7a68)[0x7f0514265a68]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x374bd0)[0x7f05143e2bd0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(PMPIDI_CH3I_Progress+0x2008)[0x7f05141a6bc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x29e1e0)[0x7f051430c1e0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x110cc8)[0x7f051417ecc8]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x1102a0)[0x7f051417e2a0]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x113250)[0x7f0514181250]
/cluster/software/impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libmpi.so.12(+0x350b7c)[0x7f05143beb7c]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN4Dune6CpGrid11scatterGridB5cxx11ENS_16EdgeWeightMethodEbPKSt6vectorIN3Opm4WellESaIS4_EEPKdbi+0x1a4)[0x171d6a4]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm17EclCpGridVanguardINS_10Properties4TTag14EclFlowProblemEE11loadBalanceEv+0x479)[0xced609]
/cluster/home/kjetilly/sigma2/opm/opm-simulators/build/bin/flow(_ZN3Opm9SimulatorINS_10Properties4TTag14EclFlowProblemEEC1Eb+0x721)[0xd96b71]
Copying output/NORNE_ATW2013.1.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.10.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.11.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.12.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.13.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.14.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.16.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.17.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.18.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.19.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.2.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.20.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.21.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.3.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.4.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.5.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.6.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.7.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.8.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.9.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/NORNE_ATW2013.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_0.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_1.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_10.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_11.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_12.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_13.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_14.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_16.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_17.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_18.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_19.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_2.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_20.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_21.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_3.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_4.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_5.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_6.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_7.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_8.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/last_line_seen_9.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_0_11.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_0_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_10_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_11_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_12_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_13_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_14_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_15_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_16_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_17_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_18_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_19_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_1_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_20_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_21_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_2_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_3_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_4_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_5_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_6_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_7_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_8_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1
Copying output/stacktrace_9_15.DBG to /cluster/home/kjetilly/opm-hpc-benchmarking/sims/NORNE_ATW2013_processors22_threads1

Task and CPU usage stats:
       JobID    JobName  AllocCPUS   NTasks     MinCPU MinCPUTask     AveCPU    Elapsed ExitCode 
------------ ---------- ---------- -------- ---------- ---------- ---------- ---------- -------- 
873290       NORNE_ATW+         22                                             01:00:05      0:0 
873290.batch      batch          1        1   00:00:01          0   00:00:01   01:00:06     0:15 
873290.exte+     extern         22        6   00:00:00          5   00:00:00   01:00:05      0:0 
873290.0           flow         22       22   00:59:26          0   01:00:15   01:00:31      1:0 

Memory usage stats:
       JobID     MaxRSS MaxRSSTask     AveRSS MaxPages   MaxPagesTask   AvePages 
------------ ---------- ---------- ---------- -------- -------------- ---------- 
873290                                                                           
873290.batch      4512K          0      4512K       18              0         18 
873290.exte+          0          5          0        0              5          0 
873290.0        266868K          0   75108910      330             18        229 

Disk usage stats:
       JobID  MaxDiskRead MaxDiskReadTask    AveDiskRead MaxDiskWrite MaxDiskWriteTask   AveDiskWrite 
------------ ------------ --------------- -------------- ------------ ---------------- -------------- 
873290                                                                                                
873290.batch       48.82M               0         48.82M       30.14M                0         30.14M 
873290.exte+        0.00M               5          0.00M            0                5              0 
873290.0           27.64M               0          2.87M        0.93M                0          0.06M 

Job 873290 completed at Thu Jun 11 20:17:54 CEST 2020
```

### PR DESCRIPTION
**Pull request by blattms**
This fixes quite a few bugs in the code moving cells  (to keep all cells perforated by a well on one process in case the loadbalancer violates this request) .
The code has been tested with a model by @akva2 and  artifically tested by forcing all wells to be moved to the process with the highest rank. Both tests run successfully on my system.
Closes #476

The problem is that on my system usually no wells get moved ~(even with @akva2 's problem and 64 processes)~. Tested @akva2 's model with `--edge-weights-method=0` and 32 processes. Please test further.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

File: opm/grid/common/WellConnections.cpp [hunk 1]
```diff
@@ -147,47 +149,37 @@ postProcessPartitioningForWells(std::vector<int>& parts,
                                          return (p1.second > p2.second);
                                      })
                     ->first;
+                // trigger code \todo remove after debugging
```
Comment (atgeirr) [inline opm/grid/common/WellConnections.cpp:152]: You think we should test this PR with these forced migrations before removing and testing again without?

Comment (blattms) [reply opm/grid/common/WellConnections.cpp:152]: Shoot. That rebase went south.

**Comment by blattms** [comment]
rebased the rebase to remove trigger code.

**Comment by blattms** [comment]
reread @akva2 instructions. Turned out I missed one option (see edited description) and I was able to get a successful run with 32 processors that moved one well.

**Comment by blattms** [comment]
jenkins build this parallel serial please

**Comment by blattms** [comment]
jenkins run norne please

**Comment by blattms** [comment]
Fixed all the issues. Will selfmerge tomorrow as this definitely fixes issue.
